---
---

<center><h1> Basics of NumPy </h1></center>

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

 - A powerful N-dimentional array object
 - Sophisticated (Broadcasting) functions
 - Tools for integrating C/C++ and fortran code
 - Useful linear algebra, Fourier transform, and randam number capabilities
 
 
 ***Source:***https://numpy.org/
 
 ---

In [1]:
# importing the NumPy library
import numpy as np

***If you got an error while runing the above cell, import it by using the following command.***


***`!pip3 install numpy`***

---

In [2]:
# check version of the numpy library
np.__version__

'1.20.1'

In [3]:
# create numpy array
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [4]:
[1, 4, '2', 5, False]

[1, 4, '2', 5, False]

***The difference between numpy array and list***


- Data type should be same of all the elements in a numpy array. whereas it can be different in case of lists.
- **Broadcasting:** https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

---
---

In [6]:
# if we add an element of string data type in a numpy array
# then it will upcast the data type to string of the all the element
np.array([1, 4, '2', 5, False])

array(['1', '4', '2', '5', 'False'], dtype='<U11')

***Now, we will create one sample list and numpy array and apply a very basic function of multiplication by 2. We will see that in case of list the elements are duplicated and appended to the list whereas in case of numpy array we got an array where all elements are multiplied by 2.***

----

In [11]:
# sample list
sample_list = [1, 2, 3, 4, 5, 6]
sample_list

[1, 2, 3, 4, 5, 6]

In [8]:
sample_list*2

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [13]:
#numpy array
sample_numpy_array = np.array([1, 2, 3, 4, 5, 6])
sample_numpy_array

array([1, 2, 3, 4, 5, 6])

In [14]:
sample_numpy_array*2

array([ 2,  4,  6,  8, 10, 12])

---

***Creating matrix using numpy***

---

In [15]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

In [16]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
#matrix
a=np.array(a)

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#accesing element 2
a[0][1]

2

In [21]:
#accesing element 5
a[1][1]

5

In [22]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
#creating a 3x3 array of random integers in the interval (0,10)
np.random.randint(0,10,(3, 3))

array([[6, 2, 9],
       [2, 7, 1],
       [2, 1, 3]])

In [25]:
# create another matrix
np.random.randint(0,10,(3,3))

array([[3, 8, 2],
       [9, 0, 4],
       [3, 4, 8]])

***We got a different matrix when generated another random matrix. We can get the same matrix again by fixing the seed. Let's see how?*** 

---

In [28]:
#fixing the random seed
np.random.seed(0)
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [30]:
#Create a matrix 3x4 interger array filled with zeros
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [31]:
#Create a matrix 4x5 interger array filled with zeros
np.zeros((4,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
# Create a 2 X 10 integer array filled with ones
np.ones((2,10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [35]:
# Create a 4 X 5 integer array filled with ones
np.ones((4,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

***Identity matrix***

In [36]:
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

***create a matrix of filled with any specific number of specific dimension.***

---

In [37]:
# Create a 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [38]:
# Create a 2x4 array filled with 8
np.full((2,4), 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])


---
***Array concatenation:***

---

In [42]:
matrix1 = np.array([[1,2,3],
                  [4,5,6]])
print("matrix1")
matrix1

matrix1


array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
matrix2 = np.array([[7,8,9],
                   [10,11,12]])
print("matrix2")
matrix2

matrix2


array([[ 7,  8,  9],
       [10, 11, 12]])

***Row wise concatenation***


In [46]:
matrix_1_combinedRow = np.concatenate([matrix1, matrix2], axis=0)
print("Combined on row (axis=0)")
matrix_1_combinedRow

Combined on row (axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

***Column wise concatenation***


In [47]:
matrix_1_2_combinedCol = np.concatenate([matrix1, matrix2], axis=1)
print("Combined on Column (axis=1)")
matrix_1_2_combinedCol

Combined on Column (axis=1)


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

***Learn more about the numpy here: https://numpy.org/doc/1.17/user/index.html***

---
---